config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :galleries do
    resources :images
  end

  root 'home#index'
  get 'home/index'
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery, dependent: :destroy

  has_attached_file :attachment, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>',
    large: '900x300>',
  }

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_galleries = Gallery.includes(:images).order("created_at desc").limit(5)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @gallery = Gallery.find(params[:gallery_id])
    @image = @gallery.images.new(image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json do
          data = { id: @image.id, thumb: view_context.image_tag(@image.attachment.url(:thumb))}
          render json: data, status: :created#, location: @image
        end
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def image_params
    params.require(:image).permit(:attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <%= f.submit 'Submit', class: 'button small' %>
<% end %>

app/views/galleries/edit.html.erb
<h3>Editing gallery</h3>

<%= render 'form' %>

<div id="upload">
  <div id="dropzone" class="panel">Drop files here</div>
  <input id="fileupload" data-url="/galleries/<%= @gallery.id %>/images" multiple="" name="image[attachment]" type="file" />
</div>

app/views/galleries/index.html.erb
<h3>Listing galleries</h3>

<%= link_to 'New Gallery', new_gallery_path, class: 'button small' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td style="width: 70%"><%= gallery.name %></td>
        <td style="width: 30%">
          <ul class="button-group">
            <li><%= link_to 'Show', gallery, class: 'button tiny' %></li>
            <li><%= link_to 'Edit', edit_gallery_path(gallery), class: 'button tiny' %></li>
            <li><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny alert' %></li>
          </ul>
        </td>
      </tr>
    <% end %>
    <% if @galleries.size == 0 %>
      <tr>
        <td colspan="2">No galleries</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Gallery', new_gallery_path, class: 'button small' %>

app/views/galleries/new.html.erb
<h3>New gallery</h3>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
</p>

<div class="row">
  <% if @gallery.images.size > 0 %>
    <div class="large-6 columns">
      <ul data-orbit>
      <% @gallery.images.each do |image| %>
        <li><%= image_tag image.attachment(:large) %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @gallery.images.size == 0 %>
    <p>No images for this gallery. <%= link_to "Please upload some.", edit_gallery_path(@gallery) %></p>
  <% end %>
</div>

app/views/home/index.html.erb
<h3>Recent Galleries</h3>

<ul class="large-block-grid-2">
  <% @recent_galleries.each do |gallery| %>
    <% if gallery.images.size > 0 %>
      <li>
          <ul data-orbit>
            <% gallery.images.each do |image| %>
              <li>
                <%= link_to image_tag(image.attachment(:large)), gallery_path(gallery) %>
                <div class="orbit-caption">
                  <%= gallery.name %>
                </div>
              </li>
            <% end %>
          </ul>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Image Gallery" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar foundation-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
         <h1><%= link_to "Image Gallery", root_path %></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul>
          <li<%= ' class=active' if controller.controller_name == 'galleries' %>><%= link_to "Galleries", galleries_path %></li>
        </ul>
      </section>
    </nav>

    <section class="main-section">
      <div class="row">
        <div class="large-12 columns">
          <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </section>
    <%= javascript_include_tag "application" %>
  </body>
</html>